### ISSUE TITLE
Potential alternative approach (CSP beware?)

### ISSUE THREAD

**Issue by ggoodman** [WebReflection/buffer-to-base64#1]
```js
async function base64StringToByteStream(base64, contentType, encoding = undefined) {
  const req = await fetch(`data:application/octet-stream;base64,${base64}`);
  
  let stream = req.body;
  
  if (encoding) {
    stream = stream.pipeThrough(new DecompressionStream(encoding));
  }
  
  return new Response(stream, { headers: { 'content-type': contentType }}).arrayBuffer();
}
```

This seems to be almost 2x faster: [jsbenchmark.com](https://jsbenchmark.com/#eyJjYXNlcyI6W3siaWQiOiJjT09fYkxsc0NhU3NYVkd2cE5ZbDQiLCJjb2RlIjoiY29uc3QgYnVmID0gYXdhaXQgYmFzZTY0U3RyaW5nVG9CeXRlU3RyZWFtKFwiSDRzSUFBdFNaMllBQTJOSUxNNWxaR0JnWUd4dmFHaGdZRXhncXE5bnJHZHVBbk1ZV0pzaHRDRDdCQkNEaVMwM05UZS9xSktKZ1RreEpZV0JnYXNUTE0zT29NQ293SkRGemIydEJhU0l3YkdoNFFBRE53ZklWQ1lnWm5Ec0FQSG5zRENNZ2xHQUMwd0VKU1dXdk1UY1ZNWTJTS0lEcDdGL0lEWm5RVkYrU21seWFsRXhFMGRPWWw1NmFXSjZLaU5MVUdseENZdVJnYUVGRDFBNk9iVzRPRFZGTjZtU21iVUlLSjRzYTZobmJLSm5xS0NSbG14cWtHWnNaSkdrQUZScXFXdGdvbXRrb3NsV25wZ0RWTVpxb0dldVo4QlREc3dDdWttWmVTbnBxWGxDQm5wR2VpYW1DaHBtYVlsbWlXbEd4a21hQUc2L1VUa2lBd0FBXCIsICdhcHBsaWNhdGlvbi93YXNtJywgJ2d6aXAnKTtcblxuaWYgKGJ1Zi5ieXRlTGVuZ3RoICE9IDgwMikge1xuICB0aHJvdyBuZXcgRXJyb3IoYEludmFsaWQgc2l6ZTogd2FudCA4MDIsIGdvdCAke2J1Zi5ieXRlTGVuZ3RofWApXG59IiwiZGVwZW5kZW5jaWVzIjpbXSwiYXN5bmMiOnRydWV9LHsiaWQiOiI3VVFzVW5ReHEzYW9icUVjTkFOeHIiLCJjb2RlIjoiY29uc3QgYnVmID0gYXdhaXQgYnRvYWRlY29kZShcIkg0c0lBQXRTWjJZQUEyTklMTTVsWkdCZ1lHeHZhR2hnWUV4Z3FxOW5yR2R1QW5NWVdKc2h0Q0Q3QkJDRGlTMDNOVGUvcUpLSmdUa3hKWVdCZ2FzVExNM09vTUNvd0pERnpiMnRCYVNJd2JHaDRRQUROd2ZJVkNZZ1puRHNBUEhuc0RDTWdsR0FDMHdFSlNXV3ZNVGNWTVkyU0tJRHA3Ri9JRFpuUVZGK1NtbHlhbEV4RTBkT1lsNTZhV0o2S2lOTFVHbHhDWXVSZ2FFRkQxQTZPYlc0T0RWRk42bVNtYlVJS0o0c2E2aG5iS0pucUtDUmxteHFrR1pzWkpHa0FGUnFxV3Rnb210a29zbFducGdEVk1acW9HZXVaOEJURHN3Q3VrbVplU25wcVhsQ0JucEdlaWFtQ2hwbWFZbG1pV2xHeGttYUFHNi9VVGtpQXdBQVwiLCAnZ3ppcCcpO1xuXG5pZiAoYnVmLmJ5dGVMZW5ndGggIT0gODAyKSB7XG4gIHRocm93IG5ldyBFcnJvcihgSW52YWxpZCBzaXplOiB3YW50IDgwMiwgZ290ICR7YnVmLmJ5dGVMZW5ndGh9YClcbn0iLCJkZXBlbmRlbmNpZXMiOltdLCJhc3luYyI6dHJ1ZX1dLCJjb25maWciOnsibmFtZSI6IiIsInBhcmFsbGVsIjp0cnVlLCJkYXRhQ29kZSI6ImFzeW5jIGZ1bmN0aW9uIGJhc2U2NFN0cmluZ1RvQnl0ZVN0cmVhbShiYXNlNjQsIGNvbnRlbnRUeXBlLCBlbmNvZGluZyA9IHVuZGVmaW5lZCkge1xuICBjb25zdCByZXEgPSBhd2FpdCBmZXRjaChgZGF0YTphcHBsaWNhdGlvbi9vY3RldC1zdHJlYW07YmFzZTY0LCR7YmFzZTY0fWApO1xuICBcbiAgbGV0IHN0cmVhbSA9IHJlcS5ib2R5O1xuICBcbiAgaWYgKGVuY29kaW5nKSB7XG4gICAgc3RyZWFtID0gc3RyZWFtLnBpcGVUaHJvdWdoKG5ldyBEZWNvbXByZXNzaW9uU3RyZWFtKGVuY29kaW5nKSk7XG4gIH1cbiAgXG4gIHJldHVybiBuZXcgUmVzcG9uc2Uoc3RyZWFtLCB7IGhlYWRlcnM6IHsgJ2NvbnRlbnQtdHlwZSc6IGNvbnRlbnRUeXBlIH19KS5hcnJheUJ1ZmZlcigpO1xufVxuZ2xvYmFsVGhpcy5iYXNlNjRTdHJpbmdUb0J5dGVTdHJlYW0gPSBiYXNlNjRTdHJpbmdUb0J5dGVTdHJlYW07XG5cbmNvbnN0IGRlY29kZSA9IGFzeW5jIChib3RhLCBmb3JtYXQgPSAnZGVmbGF0ZScpID0-IHtcbiAgY29uc3Qgc3RyID0gYXRvYihib3RhKTtcbiAgY29uc3QgYnVmZmVyID0gbmV3IFVpbnQ4QXJyYXkoc3RyLmxlbmd0aCk7XG4gIGZvciAobGV0IGkgPSAwOyBpIDwgc3RyLmxlbmd0aDsgaSsrKVxuICAgIGJ1ZmZlcltpXSA9IHN0ci5jaGFyQ29kZUF0KGkpO1xuICBsZXQgcmVzcG9uc2UgPSBuZXcgQmxvYihbYnVmZmVyXSk7XG4gIGlmIChmb3JtYXQpIHtcbiAgICBjb25zdCBzdHJlYW0gPSBuZXcgRGVjb21wcmVzc2lvblN0cmVhbShmb3JtYXQpO1xuICAgIHJlc3BvbnNlID0gcmVzcG9uc2Uuc3RyZWFtKCkucGlwZVRocm91Z2goc3RyZWFtKTtcbiAgfVxuICByZXR1cm4gYXdhaXQgbmV3IFJlc3BvbnNlKHJlc3BvbnNlKS5hcnJheUJ1ZmZlcigpO1xufTtcbmdsb2JhbFRoaXMuYnRvYWRlY29kZSA9IGRlY29kZTsiLCJnbG9iYWxUZXN0Q29uZmlnIjp7ImRlcGVuZGVuY2llcyI6W119fX0)

**Comment by ggoodman** [comment]
Err, the `contentType` was from a failed experiment and shouldn't be in the suggestion but also shouldn't really change the behaviour.

**Comment by WebReflection** [comment]
I like the idea, just wondering if it’d work on NodeJS, Deno, or even Bun (without format) … I’ll test all the things tomorrow and eventually implement it as it’s also less code/overhead and it makes sense. Is CSP any better in here and, if that’s the case, why is that? Or this is more CSP hostile? 🤔

**Comment by ggoodman** [comment]
I tested successfully in Node 20 ✅.

**Comment by WebReflection** [comment]
It’s 3x faster on my iPhone so I’m sold, however I’d like to keep CSP concerns in mind so I’m planning to add a stream utility instead that can be used to also init stream in WebAssembly or it can be awaited as arrayBuffer… that would cover all use cases:
  * encode / decode without CSP issues
  * faster decode when CSP is not a concern
  * direct stream when the goal is to serve the buffer via content type and CSP is not a concern

thoughts?

**Comment by WebReflection** [comment]
I went ahead and added the extra `stream` method to decode with your fast suggestion. I am still puzzled if that application/octet-stream is actually needed at all in there but the logic feels right and clean anyway, and compressing the utility should play pretty well.

Everything works in both NodeJS and browsers (added test/index.html too) but it'd be lovely if you could confirm the current `Response` works to initialize WebAssembly ... this is the actual logic: https://github.com/WebReflection/buffer-to-base64/blob/main/esm/stream.js

**Comment by ggoodman** [comment]
Not sure that the content type is essential. It seemed correct 🤷‍♂️

**Comment by WebReflection** [comment]
@ggoodman to clarify, to have a WASM usable it's gonna have the right `application/wasm` content type as response, my question was rather around the fetch data URL using an `application/octet-stream` which is probably not necessary but indeed it feels correct.
